### PR TITLE
Dependencies upgrade with fixes + version bump

### PR DESCRIPTION
**Pull request by Keytwo**
Hi, 

I just managed to upgrade some dependency in order to make this plugin compatible with new node.js.
Would you mind to merge into a new version?

My bests!

### CODE REVIEW

**Comment by davidtheclark** [comment]
@Keytwo Would you like to take over as maintainer for this project? I have not been using it for a long time now, and it would be better off in the hands of someone actively using it. What do you think?

**Comment by Keytwo** [comment]
Hi @davidtheclark,
Yes, I understand and I appreciate your offer. The company where I work will take care of that if you wish.
The ownership can be moved to "openmindlab".

Thank you for your work! ;)

**Comment by davidtheclark** [comment]
@Keytwo I cannot transfer ownership because you have a fork of the same name. If you delete your fork, I can transfer ownership of the repo; then I'll add you as a collaborator on npm so you can publish.

**Comment by Keytwo** [comment]
@davidtheclark it's ok now, the repo has been deleted ;)

**Comment by benib** [comment]
While doing maintenance on ownership and collaborator. I have the same problem that I do not use the project anymore, and probably never will again. So you can remove any access rights for me.

Happy to see the project going to someone who uses it.

**Comment by davidtheclark** [comment]
@Keytwo Haven't done this before and realizing it's tricky. Looks like (https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization) we have two options:
- Make me a temporary admin in the org and I can't transfer ownership
- OR just fork it, and in this repo we'll add a link to your fork. — And who should I give npm rights to?

**Comment by Keytwo** [comment]
Hi @davidtheclark, sorry for the delay.
I think the second option will fit better since I don't think the first can be viable (due to company policies).
For NPM I'll ask to my CTO and let you know ASAP.

Thanks for your collaboration ;)

**Comment by davidtheclark** [comment]
Ok. Once we give you npm ownership, just send a PR to this repo altering the readme to say that the maintained version is over at your fork.

**Comment by Keytwo** [comment]
Hi @davidtheclark,
we had setup an account for our company on npm. The user is "openmindlab".
Let me know when you'll switch the ownership.

My bests!

**Comment by davidtheclark** [comment]
@Keytwo I've added you as a collaborator on this repo so you can publish changes to the README, etc., and added `openmindlab` as a publisher on npm. Let me know if you need anything else!

**Pull request closed without merging**
